blank_issues_enabled: true
contact_links:
  - name: Discussions
    url: https://github.com/Stellar-Ecosystem/lodestar/discussions
    about: Please ask and answer questions here.
  - name: Stellar Network
    url: https://stellar.org
    about: Learn more about the Stellar network.
